[package]
name = "kebabify"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
walkdir = "2.4"
regex = "1.10"

[dev-dependencies]
tempfile = "3.8"
